global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'catv-transcoding'
    environment: 'production'

scrape_configs:
  # Multiple transcoders
  - job_name: 'hjstreams'
    static_configs:
      - targets: 
          - 'localhost:9090'  # transcoder-01
          - 'localhost:9091'  # transcoder-02
        labels:
          service: 'transcoder'
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '.*:(\d+)'
        replacement: 'transcoder-$1'